### ISSUE TITLE
Multiple questo pages upload and search

### ISSUE THREAD

**Issue by DDDOlga** [LaDHUL/drawings-gods#8]
2017.06.06
Questinnaries having multiple pages, same code, but ending -s, -t, etc.
I have uploaded the first page of the questo and filled in the transcribed questo.
I cannot, however, process with the second page from the first, so I tried to upload the -s page independently. Independent stuff does not work, has misisng lisnks, i.e. the only way to process the questo is to upload ALL the files from the start.
Tried that, upload was successful, but still cannot locate the -s page of the questionnary in search.

Likely the test version that Marion showed at the meeting are not yet integrated into http://platec.unil.ch/salsah/ version.

**Comment by mrivoal** [comment]
I don't understand. Please, be more specific or join some screenshot.
