### ISSUE TITLE
Links from recto to collsite, campagne and passage

### ISSUE THREAD

**Issue by DDDOlga** [LaDHUL/drawings-gods#9]
Need a straight link from image to coll site and to passage, or via passage.
At the moment impossible to go from drawing to coll site or passage, and this is crucial. 
Same concerns the campagne, i.e. the team should be able to navigate from a drawing to campagne, collsite and passage, at the same time, in campagne, coll site and passage should be an "index" of all related drawings.

**Comment by mrivoal** [comment]
Closed by 170d9cfba80c895dfe7c124f417410148337ea08
